image: blang/latex

before_script:
  - apt-get update -qq && apt-get install -y -qq texlive-full

build:
  script:
    - cd Report/
    - pdflatex -interaction=nonstopmode report
    - biber report
    - pdflatex -interaction=nonstopmode report
  artifacts:
    paths:
      - Report/report.pdf
